Repository BHoM/Excel_Toolkit, pull requests merged in 2023-11, with the labels that each got.

#41 Add support for stream in the adapter
  Excel_Adapter/AdapterActions/Pull.cs
  Excel_Adapter/AdapterActions/Push.cs
  Excel_Adapter/CRUD/Read/Read.cs
  Excel_Adapter/ExcelAdapter.cs
  Excel_Adapter/Excel_Adapter.csproj
Labels: type:feature

#43 Add ClosedXML dependency to nuspec
  .ci/BHoMBot/Nuget/BHoM.Interop.Excel.nuspec
Labels: type:compliance

#46 Adding copy of OpenXML in post build events
  Excel_Adapter/Excel_Adapter.csproj
Labels: type:bug

#47 Update nuget package to match PowerPoint Toolkit
  Excel_Adapter/Excel_Adapter.csproj
Labels: type:bug
