Repository BHoM/Excel_Toolkit, pull requests merged in 2024-01, with the labels that each got.

#52 Update readme link
  README.md
Labels: type:documentation

#54 Add ability to push multiple tables without reopening the file every time
  Excel_Adapter/AdapterActions/Push.cs
  Excel_oM/PushItem.cs
Labels: type:feature

#55 Remove unnecessary using which is preventing ZeroCodeTool build
  Excel_Adapter/AdapterActions/Push.cs
  altConfigs.txt
Labels: type:bug

#58 ClosedXML Version Updated
  Excel_Adapter/Convert/FromExcel/CellContents.cs
  Excel_Adapter/Excel_Adapter.csproj
  Excel_Adapter/packages.config
  Excel_oM/packages.config
Labels: type:bug
